"""CLI client tracking model.

Tracks installed Preloop CLI clients that phone home during their daily
version check (``POST /api/v1/cli/version-check``, instance_tracker plugin).
One row per installed client, keyed by the ``client_id`` the CLI generates
and persists in its config directory at install/first-run time.

    CLI (daily) ──▶ /api/v1/cli/version-check
                       │ upsert by client_id
                       ▼
                  cli_clients row ── last_seen = last version check
                       │ new row / IP change
                       ▼
                  ip-api.com geolocation (country/city/lat/lon)
                       ▼
                  /admin/cli-clients (list) + /admin/map (map)

Privacy: the CLI never sends its bearer token here — only a SHA-256 prefix
fingerprint (non-reversible), the server URL it is configured against, and
its version/platform. ``account_id`` is resolved server-side only when the
client is authenticated against THIS server and presented a valid token.
"""

import uuid
from datetime import datetime
from typing import Any, Dict, Optional

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from .base import Base


class CliClient(Base):
    """One installed Preloop CLI, updated on every version check."""

    __tablename__ = "cli_clients"

    # Core identity
    client_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique identifier generated by the CLI at install/first run",
    )
    cli_version: Mapped[str] = mapped_column(
        String(50), nullable=False, comment="CLI version at last check-in"
    )
    os: Mapped[Optional[str]] = mapped_column(
        String(30), nullable=True, comment="GOOS, e.g. darwin/linux/windows"
    )
    arch: Mapped[Optional[str]] = mapped_column(
        String(30), nullable=True, comment="GOARCH, e.g. arm64/amd64"
    )

    # What the client is authenticated against
    preloop_url: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        index=True,
        comment="Preloop server URL the CLI is configured/authenticated with",
    )
    token_fingerprint: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        index=True,
        comment="SHA-256 prefix of the CLI's access token (non-reversible)",
    )
    account_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("account.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Account resolved from bearer auth when checking in against this server",
    )

    # Network + check-in bookkeeping
    ip_address: Mapped[Optional[str]] = mapped_column(
        String(45), nullable=True, comment="Last known IP address (IPv4 or IPv6)"
    )
    first_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="First check-in",
    )
    last_seen: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
        comment="Datetime of the last version check",
    )
    check_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, comment="Number of version checks"
    )

    # Geolocation (from last known IP)
    country: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    country_code: Mapped[Optional[str]] = mapped_column(String(2), nullable=True)
    city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    region: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    lat: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    lon: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    metadata_: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        "metadata", JSONB, nullable=True, comment="Additional client metadata"
    )

    account = relationship("Account")

    def __repr__(self) -> str:
        return (
            f"<CliClient {self.client_id} v{self.cli_version} "
            f"url={self.preloop_url} last_seen={self.last_seen}>"
        )
