"""add cli_clients table for CLI version-check telemetry

Revision ID: 20260710_cli_clients
Revises: 20260706_aw_name_uq
Create Date: 2026-07-10
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision: str = "20260710_cli_clients"
down_revision: Union[str, None] = "20260706_aw_name_uq"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the CLI client tracking table."""
    op.create_table(
        "cli_clients",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, index=True),
        sa.Column(
            "client_id",
            UUID(as_uuid=True),
            nullable=False,
            unique=True,
            index=True,
            comment="Unique identifier generated by the CLI at install/first run",
        ),
        sa.Column("cli_version", sa.String(50), nullable=False),
        sa.Column("os", sa.String(30), nullable=True),
        sa.Column("arch", sa.String(30), nullable=True),
        sa.Column("preloop_url", sa.String(500), nullable=True, index=True),
        sa.Column("token_fingerprint", sa.String(64), nullable=True, index=True),
        sa.Column(
            "account_id",
            UUID(as_uuid=True),
            sa.ForeignKey("account.id", ondelete="SET NULL"),
            nullable=True,
            index=True,
        ),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            index=True,
        ),
        sa.Column("check_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("country", sa.String(100), nullable=True),
        sa.Column("country_code", sa.String(2), nullable=True),
        sa.Column("city", sa.String(100), nullable=True),
        sa.Column("region", sa.String(100), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("metadata", JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Drop the CLI client tracking table."""
    op.drop_table("cli_clients")
